[package]
name = "safe-mac-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
clap = { version = "2.29.4"}
sha256 = "1.1.1"
mac_address = { version = "1.1.4" }
pnet = "0.31.0"